rem ÉèÖÃUltraAgentÂ·¾¶
net use Y: \\10.156.163.53\Cloud_Archive_V100R003C00_Agent

SET ULTRAAGENT_PROJECT_CLASS_PATH=Y:\Package
SET ULTRAAGENT_PROJECT_TMP_PATH=Y:\temp

IF EXIST "%ULTRAAGENT_PROJECT_CLASS_PATH%\"         DEL "%ULTRAAGENT_PROJECT_CLASS_PATH%\*" /F /Q

IF EXIST "%ULTRAAGENT_PROJECT_TMP_PATH%\AIX\"         DEL "%ULTRAAGENT_PROJECT_TMP_PATH%\AIX\*" /F /Q

IF EXIST "%ULTRAAGENT_PROJECT_TMP_PATH%\RHEL5\"         DEL "%ULTRAAGENT_PROJECT_TMP_PATH%\RHEL5\*" /F /Q

IF EXIST "%ULTRAAGENT_PROJECT_TMP_PATH%\RHEL6\"         DEL "%ULTRAAGENT_PROJECT_TMP_PATH%\RHEL6\*" /F /Q

IF EXIST "%ULTRAAGENT_PROJECT_TMP_PATH%\SLES10\"         DEL "%ULTRAAGENT_PROJECT_TMP_PATH%\SLES10\*" /F /Q

IF EXIST "%ULTRAAGENT_PROJECT_TMP_PATH%\SLES11\"         DEL "%ULTRAAGENT_PROJECT_TMP_PATH%\SLES11\*" /F /Q

IF EXIST "%ULTRAAGENT_PROJECT_TMP_PATH%\Windows\"         DEL "%ULTRAAGENT_PROJECT_TMP_PATH%\Windows\*" /F /Q

timeout 2 > nul
net use Y: /delete /Y
